import { useCallback, useEffect, useMemo, useState } from "react";
import type { FormEvent } from "react";
import type { CheckDto } from "../shared/domain";
import { api } from "./api";

const initialForm = { name: "", kind: "period" as "period" | "cron", periodSeconds: "3600", expression: "0 2 * * *", timezone: "UTC", graceSeconds: "300" };
function pingUrl(check: CheckDto): string { return `${window.location.origin}/ping/${check.pingToken}`; }

export default function App() {
  const [checks, setChecks] = useState<CheckDto[]>([]); const [form, setForm] = useState(initialForm); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null);
  const load = useCallback(async () => { try { setError(null); setChecks(await api.list()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to load checks"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30_000); return () => window.clearInterval(timer); }, [load]);
  const create = async (event: FormEvent) => { event.preventDefault(); const schedule = form.kind === "period" ? { kind: "period" as const, periodSeconds: Number(form.periodSeconds) } : { kind: "cron" as const, expression: form.expression, timezone: form.timezone }; try { await api.create({ name: form.name, schedule, graceSeconds: Number(form.graceSeconds) }); setForm(initialForm); setNotice("Check created"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create check"); } };
  const copy = async (check: CheckDto) => { await navigator.clipboard.writeText(pingUrl(check)); setNotice("Ping URL copied"); };
  const remove = async (check: CheckDto) => { if (!window.confirm(`Delete ${check.name}?`)) return; await api.remove(check.id); await load(); };
  const toggle = async (check: CheckDto) => { if (check.status === "paused") await api.resume(check.id); else await api.pause(check.id); await load(); };
  const nextLabel = useMemo(() => form.kind === "period" ? "Every period" : "Cron expression", [form.kind]);
  return <main className="app-shell"><nav className="nav"><a className="brand" href="/" aria-label="CronUp home"><span className="brand-mark">C</span><span>CronUp</span></a><div className="nav-links"><a className="nav-link active" href="#checks">Checks</a><button className="nav-button" onClick={() => void api.slackTest().then(() => setNotice("Slack test sent")).catch((cause) => setError(cause instanceof Error ? cause.message : "Slack test failed"))}>Test Slack</button></div></nav><div className="content"><header className="page-header"><div><p className="eyebrow">Private cron monitoring</p><h1>My checks</h1><p className="subhead">Private dead-man switches on your Cloudflare account.</p></div><button className="primary add-button" onClick={() => document.getElementById("new-check")?.scrollIntoView({ behavior: "smooth" })}>+ New check</button></header>
    {notice && <p className="notice" role="status">{notice}</p>}{error && <div className="error" role="alert">{error}<button onClick={() => void load()}>Retry</button></div>}
    <section className="workspace" id="checks"><div className="list-toolbar"><div><h2>Checks</h2><p className="toolbar-meta">{checks.length} configured checks</p></div><span className="live"><span className="live-dot" /> Live</span></div><div className="check-table"><div className="table-head"><span>Status</span><span>Check</span><span>Schedule</span><span>Last ping</span><span /></div>{loading ? <p className="muted table-empty">Loading checks...</p> : checks.length === 0 ? <p className="muted table-empty">No checks yet.</p> : checks.map((check) => <article className="check-row" key={check.id}><div><span className={`status status-${check.status}`}><span className="status-dot" />{check.status}</span></div><div className="check-name"><h3>{check.name}</h3><code>{pingUrl(check)}</code></div><div className="schedule"><strong>{check.schedule.kind === "period" ? `Every ${check.schedule.periodSeconds}s` : check.schedule.expression}</strong><span>Grace {check.graceSeconds}s{check.schedule.kind === "cron" ? ` · ${check.schedule.timezone}` : ""}</span></div><div className="last-ping">{check.lastPingAt ? new Date(check.lastPingAt).toLocaleString() : "Never"}</div><div className="actions"><button title="Copy ping URL" onClick={() => void copy(check)}>Copy</button><button onClick={() => void toggle(check)}>{check.status === "paused" ? "Resume" : "Pause"}</button><button className="danger" onClick={() => void remove(check)}>Delete</button></div></article>)}</div></section>
    <section className="new-check" id="new-check"><div className="section-title"><h2>Create a check</h2><p>One success ping after each completed job.</p></div><form onSubmit={create} className="form-grid"><label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Nightly backup" /></label><label>Schedule<select value={form.kind} onChange={(e) => setForm({ ...form, kind: e.target.value as "period" | "cron" })}><option value="period">Period</option><option value="cron">Cron expression</option></select></label>{form.kind === "period" ? <label>{nextLabel} (seconds)<input type="number" min="60" value={form.periodSeconds} onChange={(e) => setForm({ ...form, periodSeconds: e.target.value })} /></label> : <><label>{nextLabel}<input value={form.expression} onChange={(e) => setForm({ ...form, expression: e.target.value })} /></label><label>Timezone<input value={form.timezone} onChange={(e) => setForm({ ...form, timezone: e.target.value })} /></label></>}<label>Grace (seconds)<input type="number" min="0" value={form.graceSeconds} onChange={(e) => setForm({ ...form, graceSeconds: e.target.value })} /></label><button className="primary" type="submit">Create check</button></form></section></div></main>;
}
